siteTitle="Sivuohje"
baseColor = "#7b1fa2"
alertColor =  "#ffeb3b"
linkPrefix = "/gatsby-starter-documentation"
navHeight = "60px"
docPages = [
  "/ohjeet/",
  "/ohjeet/hakukoneoptimointi/",
  "/ohjeet/analytiikka/",
]
